# Generated by Django 5.2.4 on 2025-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_district', models.CharField(max_length=15)),
                ('location_municipality', models.CharField(max_length=20)),
                ('location_ward_num', models.IntegerField()),
                ('room_num', models.IntegerField()),
                ('flat', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
