# Generated by Django 5.2.4 on 2025-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone_num',
            field=models.IntegerField(default=9827130656),
            preserve_default=False,
        ),
    ]
