# Generated by Django 5.2.4 on 2025-08-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_approved',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='is_cancelled',
            new_name='cancelled',
        ),
    ]
