# Generated by Django 5.2.4 on 2025-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
