# Generated by Django 5.2.4 on 2025-08-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0002_rename_is_approved_booking_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
    ]
