# Generated by Django 5.2.4 on 2025-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0002_room_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='flat',
        ),
        migrations.AddField(
            model_name='room',
            name='photos',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
