# Generated by Django 5.2.4 on 2025-07-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0002_room_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_approved',
            new_name='approval',
        ),
    ]
