# Generated by Django 5.2.4 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0003_remove_room_flat_room_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photos',
            field=models.ImageField(upload_to='room_photos/'),
        ),
    ]
