# Generated by Django 5.2.4 on 2025-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0003_remove_booking_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
