# Generated by Django 5.2.4 on 2025-07-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0003_rename_is_approved_room_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='approval',
            new_name='approve',
        ),
    ]
