# Generated by Django 5.2.4 on 2025-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0004_booking_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Rabi'),
        ),
    ]
