# Generated by Django 5.2.4 on 2025-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0004_alter_room_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_num',
            new_name='num_of_rooms_available',
        ),
    ]
