# Generated by Django 5.2.4 on 2025-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0005_booking_contact_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(),
        ),
    ]
