# Generated by Django 5.2.4 on 2025-07-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0005_rename_room_num_room_num_of_rooms_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='phone_num',
        ),
    ]
