# Generated by Django 5.2.4 on 2025-08-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0006_alter_booking_contact_alter_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='applicant_name',
        ),
    ]
