# Generated by Django 5.2.4 on 2025-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0006_remove_room_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contact_number',
            field=models.IntegerField(default=9876543210),
            preserve_default=False,
        ),
    ]
