# Generated by Django 5.2.4 on 2025-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0009_alter_room_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='location_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='location_municipality',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='location_ward_num',
            new_name='ward_num',
        ),
        migrations.AddField(
            model_name='room',
            name='province',
            field=models.CharField(default='gandaki', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='street',
            field=models.CharField(default='ramram', max_length=50),
        ),
    ]
