# Generated by Django 5.2.4 on 2025-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0011_district_province_municipality_district_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='province',
            field=models.CharField(max_length=15),
        ),
    ]
