# Generated by Django 5.2.4 on 2025-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0012_alter_room_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
