# Generated by Django 5.2.4 on 2025-07-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0013_alter_district_id_alter_municipality_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basobasnepalapp.district'),
        ),
        migrations.AlterField(
            model_name='room',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basobasnepalapp.municipality'),
        ),
        migrations.AlterField(
            model_name='room',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basobasnepalapp.province'),
        ),
    ]
