# Generated by Django 5.2.4 on 2025-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0014_alter_room_contact_number_alter_room_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='municipality',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='province',
            field=models.CharField(max_length=15),
        ),
    ]
