# Generated by Django 5.2.4 on 2025-07-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basobasnepalapp', '0015_alter_room_contact_number_alter_room_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basobasnepalapp.district'),
        ),
        migrations.AlterField(
            model_name='room',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basobasnepalapp.municipality'),
        ),
        migrations.AlterField(
            model_name='room',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basobasnepalapp.province'),
        ),
    ]
